apiVersion: v1
kind: Service
metadata:
  name: misc100
spec:
  ports:
   - port: 9999
     targetPort: 9999
  selector:
    app: misc100
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: misc100
spec:
  podSelector:
    matchLabels:
      app: misc100
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 9999
    from: []