apiVersion: v1
kind: Service
metadata:
  name: pwn50
spec:
  ports:
   - port: 9999
     targetPort: 9999
  selector:
    app: pwn50
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pwn50
spec:
  podSelector:
    matchLabels:
      app: pwn50
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 9999
    from: []