apiVersion: v1
kind: Service
metadata:
  name: comingsoon300
spec:
  ports:
   - port: 1337
     targetPort: 1337
  selector:
    app: comingsoon300
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: comingsoon300
spec:
  podSelector:
    matchLabels:
      app: comingsoon300
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 1337
    from: []