apiVersion: v1
kind: Service
metadata:
  name: clippy100
spec:
  ports:
   - port: 8000
     targetPort: 8000
  selector:
    app: clippy100
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: clippy100
spec:
  podSelector:
    matchLabels:
      app: clippy100
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8000
    from: []