apiVersion: v1
kind: Service
metadata:
  name: pinger300front
spec:
  ports:
   - port: 8080
     targetPort: 8080
  selector:
    app: pinger300front
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: pinger300front
spec:
  podSelector:
    matchLabels:
      app: pinger300front
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 8080
    from: []