apiVersion: v1
kind: Service
metadata:
  name: khronos200
spec:
  ports:
   - port: 80
     targetPort: 80
  selector:
    app: khronos200
  type: LoadBalancer
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: khronos200
spec:
  podSelector:
    matchLabels:
      app: khronos200
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - port: 80
    from: []